/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mansoor.main;

import dto.Catagory;
import dto.PointofsalePersistentManager;
import dto.ProductCriteria;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.orm.PersistentException;
import org.orm.PersistentTransaction;

/**
 *
 * @author manso
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
        updateTable();
        updateCb_Cat();
        updateChTable();
//        updateCb_ChCat();
        
    }
//    private void updateCb_ChCat() {
//        dto.Catagory[] dtoCatagories;
//        try {
//            dtoCatagories=dto.CatagoryDAO.listCatagoryByQuery(null, null);
//            for(int i=0;i<dtoCatagories.length;i++){
//                Cb_ChCatagory.addItem(dtoCatagories[i].getCAT_Name());
//            }
//        } catch (PersistentException ex) {
//            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    private void updateCb_Cat() {
        dto.Catagory[] dtoCatagories;
        try {
            dtoCatagories=dto.CatagoryDAO.listCatagoryByQuery(null, null);
            for(int i=0;i<dtoCatagories.length;i++){
                Cb_Catagories.addItem(dtoCatagories[i].getCAT_Name());
                Cb_ChCatagory.addItem(dtoCatagories[i].getCAT_Name());
            }
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateTable() {
        DefaultTableModel dm=(DefaultTableModel) jTable1.getModel();
        dm.setRowCount(0);
        dto.Product[] dtoProducts;
        
        try {
            dtoProducts = dto.ProductDAO.listProductByQuery(null, null);
            for(int i=0;i<dtoProducts.length;i++){
                Object[] temp=new Object[6];
                temp[0]=dtoProducts[i].getPROD_Code();
                temp[1]=dtoProducts[i].getPROD_Name();
                temp[2]=dtoProducts[i].getCAT_Code().getCAT_Name();
                temp[3]=dtoProducts[i].getPROD_QOH();
                temp[4]=dtoProducts[i].getPROD_MIN();
                temp[5]=dtoProducts[i].getPROD_Price();
                dm.addRow(temp);
            }
            
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void updateChTable() {
        DefaultTableModel dm=(DefaultTableModel) jTable3.getModel();
        dm.setRowCount(0);
        dto.Catagory[] dtoCatagory;
        
        try {
            dtoCatagory = dto.CatagoryDAO.listCatagoryByQuery(null, null);
            for(int i=0;i<dtoCatagory.length;i++){
                Object[] temp=new Object[2];
                temp[0]=dtoCatagory[i].getCAT_Code();
                temp[1]=dtoCatagory[i].getCAT_Name();
                dm.addRow(temp);
            }
            
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ChName = new javax.swing.JTextField();
        txt_ChQuantity = new javax.swing.JTextField();
        txt_ChMin = new javax.swing.JTextField();
        btn_SaveProdEdit = new javax.swing.JButton();
        btn_ChProduct = new javax.swing.JButton();
        btn_DelProduct = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_ChPrice = new javax.swing.JTextField();
        btn_CanProdEdit = new javax.swing.JButton();
        Cb_ChCatagory = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txt_AddName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_AddQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_AddPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_AddMin = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Cb_Catagories = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        txt_ChCatName = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btn_DelCat = new javax.swing.JButton();
        btn_SaveCat = new javax.swing.JButton();
        btn_CanCat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_CatName = new javax.swing.JTextField();
        btn_AddCat = new javax.swing.JButton();
        btn_RevCat = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Catagory", "Quantity in hand", "min threshold", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel1.setText("Name");

        jLabel2.setText("Catagory");

        jLabel3.setText("Quantity in Hand");

        jLabel4.setText("Min Threshold");

        txt_ChName.setText(" ");
        txt_ChName.setEnabled(false);
        txt_ChName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ChNameActionPerformed(evt);
            }
        });

        txt_ChQuantity.setEnabled(false);

        txt_ChMin.setEnabled(false);

        btn_SaveProdEdit.setText("Save");
        btn_SaveProdEdit.setEnabled(false);
        btn_SaveProdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveProdEditActionPerformed(evt);
            }
        });

        btn_ChProduct.setText("Edit");
        btn_ChProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChProductActionPerformed(evt);
            }
        });

        btn_DelProduct.setText("Delete");
        btn_DelProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelProductActionPerformed(evt);
            }
        });

        jLabel10.setText("Price");

        txt_ChPrice.setEnabled(false);
        txt_ChPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ChPriceActionPerformed(evt);
            }
        });

        btn_CanProdEdit.setText("Cancel");
        btn_CanProdEdit.setEnabled(false);
        btn_CanProdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CanProdEditActionPerformed(evt);
            }
        });

        Cb_ChCatagory.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_SaveProdEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_CanProdEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cb_ChCatagory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ChPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ChQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ChMin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ChName))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ChProduct)
                .addGap(18, 18, 18)
                .addComponent(btn_DelProduct)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ChName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cb_ChCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ChQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ChMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_ChPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btn_SaveProdEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_CanProdEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ChProduct)
                    .addComponent(btn_DelProduct))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Products list", jPanel1);

        txt_AddName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");

        jLabel6.setText("Catagory");

        jLabel7.setText("Quantity in hand");

        jLabel8.setText("Price");

        txt_AddPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddPriceActionPerformed(evt);
            }
        });

        jLabel9.setText("Min Threshold");

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Revert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Cb_Catagories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_CatagoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txt_AddMin)
                            .addComponent(txt_AddPrice))
                        .addContainerGap(543, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_AddName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_AddQuantity)
                                .addComponent(Cb_Catagories, 0, 100, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_AddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Cb_Catagories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_AddQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_AddPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_AddMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Product", jPanel2);

        jLabel11.setText("Catagory Name");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3);

        txt_ChCatName.setEnabled(false);
        txt_ChCatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ChCatNameActionPerformed(evt);
            }
        });

        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btn_DelCat.setText("Delete");
        btn_DelCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelCatActionPerformed(evt);
            }
        });

        btn_SaveCat.setText("Save");
        btn_SaveCat.setEnabled(false);
        btn_SaveCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveCatActionPerformed(evt);
            }
        });

        btn_CanCat.setText("Cancel");
        btn_CanCat.setEnabled(false);
        btn_CanCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CanCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_ChCatName, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_SaveCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_CanCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(btn_DelCat)
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_ChCatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btn_SaveCat)
                        .addGap(25, 25, 25)
                        .addComponent(btn_CanCat))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(btn_DelCat))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Catagories List", jPanel3);

        jLabel12.setText("Catagory Name:");

        btn_AddCat.setText("Add");
        btn_AddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddCatActionPerformed(evt);
            }
        });

        btn_RevCat.setText("Revert");
        btn_RevCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RevCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_CatName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_AddCat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_RevCat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_CatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btn_AddCat)
                .addGap(18, 18, 18)
                .addComponent(btn_RevCat)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Catagory", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_AddPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddPriceActionPerformed

    private void txt_ChNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ChNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ChNameActionPerformed

    private void txt_ChPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ChPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ChPriceActionPerformed

    private void txt_AddNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddNameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        int id = (int) jTable1.getModel().getValueAt(row, 0);
        dto.Product p=dto.ProductDAO.createProduct();
        try {
            p=dto.ProductDAO.getProductByORMID(id);
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_ChName.setText(p.getPROD_Name());
        Cb_ChCatagory.setSelectedItem(p.getCAT_Code().getCAT_Name());
        txt_ChMin.setText(p.getPROD_MIN()+"");
        txt_ChQuantity.setText(p.getPROD_QOH()+"");
        txt_ChPrice.setText(p.getPROD_Price()+"");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        txt_AddMin.setText("");
        txt_AddQuantity.setText("");
        txt_AddPrice.setText("");
        txt_AddName.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showConfirmDialog(null, "Are you sure to save the product?");
        saveProd();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void saveProd() throws HeadlessException, NumberFormatException {
        try {
            // TODO add your handling code here:
            dto.CatagoryCriteria criteria=new dto.CatagoryCriteria();
            Catagory[] c= dto.CatagoryDAO.listCatagoryByCriteria(criteria);
            dto.Product p = dto.ProductDAO.createProduct();
            p.setPROD_MIN(Integer.parseInt(txt_AddMin.getText()));
            p.setPROD_Name(txt_AddName.getText());
            p.setPROD_Price(Integer.parseInt(txt_AddPrice.getText()));
            p.setPROD_QOH(Integer.parseInt(txt_AddQuantity.getText()));
            p.setCAT_Code(c[0]);
            dto.ProductDAO.save(p);
            PersistentTransaction t=PointofsalePersistentManager.instance().getSession().beginTransaction();
            t.commit();
            updateTable();
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void Cb_CatagoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_CatagoriesActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Cb_CatagoriesActionPerformed

    private void txt_ChCatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ChCatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ChCatNameActionPerformed

    private void btn_ChProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChProductActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=-1){
            txt_ChName.setEnabled(true);
            Cb_ChCatagory.setEnabled(true);
            txt_ChMin.setEnabled(true);
            txt_ChPrice.setEnabled(true);
            txt_ChQuantity.setEnabled(true);
            btn_SaveProdEdit.setEnabled(true);
            btn_CanProdEdit.setEnabled(true);
            btn_ChProduct.setEnabled(false);
            btn_DelProduct.setEnabled(false);
            jTable1.setEnabled(false);
        } else {
        }
    }//GEN-LAST:event_btn_ChProductActionPerformed

    private void btn_CanProdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CanProdEditActionPerformed
        disableEdit();
    }//GEN-LAST:event_btn_CanProdEditActionPerformed

    public void disableEdit() {
        // TODO add your handling code here:
        txt_ChName.setEnabled(false);
        Cb_ChCatagory.setEnabled(false);
        txt_ChMin.setEnabled(false);
        txt_ChPrice.setEnabled(false);
        txt_ChQuantity.setEnabled(false);
        btn_SaveProdEdit.setEnabled(false);
        btn_CanProdEdit.setEnabled(false);
        btn_ChProduct.setEnabled(true);
        btn_DelProduct.setEnabled(true);
        jTable1.setEnabled(true);
    }

    private void btn_SaveProdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveProdEditActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int id=(int) jTable1.getModel().getValueAt(row, 0);
        try {
            updateProduct(id);
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateTable();
        disableEdit();
    }//GEN-LAST:event_btn_SaveProdEditActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jTable3.getSelectedRow()!=-1){
            txt_ChCatName.setEnabled(true);
            btn_CanCat.setEnabled(true);
            btn_SaveCat.setEnabled(true);
        } else {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int row=jTable3.getSelectedRow();
        int id = (int) jTable3.getModel().getValueAt(row, 0);
        dto.Catagory c=dto.CatagoryDAO.createCatagory();
        try {
            c=dto.CatagoryDAO.getCatagoryByORMID(id);
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_ChCatName.setText(c.getCAT_Name());
    }//GEN-LAST:event_jTable3MouseClicked

    private void btn_CanCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CanCatActionPerformed
        disCat();
    }//GEN-LAST:event_btn_CanCatActionPerformed

    private void disCat() {
        // TODO add your handling code here:
        txt_ChCatName.setEnabled(false);
        btn_CanCat.setEnabled(false);
        btn_SaveCat.setEnabled(false);
    }

    private void btn_SaveCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveCatActionPerformed
        // TODO add your handling code here:
        if (jTable3.getSelectedRow()!=-1){
        int row = jTable3.getSelectedRow();
        int id=(int) jTable3.getModel().getValueAt(row, 0);
        try {
            dto.Catagory c=dto.CatagoryDAO.getCatagoryByORMID(id);  
            c.setCAT_Name(txt_ChCatName.getText());
            dto.CatagoryDAO.save(c);
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateChTable();
        disCat();
    }
    }//GEN-LAST:event_btn_SaveCatActionPerformed

    private void btn_AddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddCatActionPerformed
        // TODO add your handling code here:
        dto.Catagory c = dto.CatagoryDAO.createCatagory();
        c.setCAT_Name(txt_CatName.getText());
        try {
           // PersistentTransaction t= dto.PointofsalePersistentManager.instance().getSession().beginTransaction();
            dto.CatagoryDAO.save(c);
           // t.commit();
        } catch (PersistentException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateChTable();
        updateCb_Cat();
        txt_CatName.setText("");
    }//GEN-LAST:event_btn_AddCatActionPerformed

    private void btn_RevCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RevCatActionPerformed
        // TODO add your handling code here:
        txt_CatName.setText("");
    }//GEN-LAST:event_btn_RevCatActionPerformed

    private void btn_DelCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelCatActionPerformed
        // TODO add your handling code here:
        if(jTable3.getSelectedRow()!=-1){
            int row = jTable3.getSelectedRow();
            int id=(int) jTable3.getModel().getValueAt(row, 0);
            try {
                dto.Catagory p = dto.CatagoryDAO.getCatagoryByORMID(id);
                dto.CatagoryDAO.delete(p);
            } catch (PersistentException ex) {
                Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
            }
            updateChTable();
        }
    }//GEN-LAST:event_btn_DelCatActionPerformed

    private void btn_DelProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelProductActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=-1){
            int row = jTable1.getSelectedRow();
            int id=(int) jTable1.getModel().getValueAt(row, 0);
            try {
                dto.Product p = dto.ProductDAO.getProductByORMID(id);
                dto.ProductDAO.delete(p);
            } catch (PersistentException ex) {
                Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
            }
            updateTable();
        }
    }//GEN-LAST:event_btn_DelProductActionPerformed

    private void updateProduct(int id) throws PersistentException, NumberFormatException {
        dto.CatagoryCriteria criteria=new dto.CatagoryCriteria();
        criteria.CAT_Name.eq((String) Cb_ChCatagory.getSelectedItem());
        Catagory[] c=dto.CatagoryDAO.listCatagoryByCriteria(criteria);
        PersistentTransaction t= dto.PointofsalePersistentManager.instance().getSession().beginTransaction();
        try {
            dto.Product p=dto.ProductDAO.getProductByORMID(id);
            p.setPROD_MIN(Integer.parseInt(txt_ChMin.getText()));
            p.setPROD_Name(txt_ChName.getText());
            p.setCAT_Code(c[0]);
            p.setPROD_Price(Integer.parseInt(txt_ChPrice.getText()));
            p.setPROD_QOH(Integer.parseInt(txt_ChQuantity.getText()));
            dto.ProductDAO.save(p);
            t.commit();
        } catch (PersistentException ex) {
            t.rollback();
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_Catagories;
    private javax.swing.JComboBox<String> Cb_ChCatagory;
    private javax.swing.JButton btn_AddCat;
    private javax.swing.JButton btn_CanCat;
    private javax.swing.JButton btn_CanProdEdit;
    private javax.swing.JButton btn_ChProduct;
    private javax.swing.JButton btn_DelCat;
    private javax.swing.JButton btn_DelProduct;
    private javax.swing.JButton btn_RevCat;
    private javax.swing.JButton btn_SaveCat;
    private javax.swing.JButton btn_SaveProdEdit;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txt_AddMin;
    private javax.swing.JTextField txt_AddName;
    private javax.swing.JTextField txt_AddPrice;
    private javax.swing.JTextField txt_AddQuantity;
    private javax.swing.JTextField txt_CatName;
    private javax.swing.JTextField txt_ChCatName;
    private javax.swing.JTextField txt_ChMin;
    private javax.swing.JTextField txt_ChName;
    private javax.swing.JTextField txt_ChPrice;
    private javax.swing.JTextField txt_ChQuantity;
    // End of variables declaration//GEN-END:variables

    
}
